name: Build and push new image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu
    steps:
      - name: build image
      - run: docker build -t shmink/flutter .
    
      - name: login
      - run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: push image
      - run: docker push shmink/flutter