name: Build and push new image

on:
  push:
    branches:
      - master

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: build arm image
        run: docker build -t shmink/flutter:arm64 .

      - name: build amd image
        run: docker build --platform linux/amd64 -t shmink/flutter:amd64 .

      - name: login
        run: docker login -u ${USERNAME} -p ${PASSWORD}

      - name: push images
        run: |
          docker push shmink/flutter:arm64
          docker push shmink/flutter:amd64